### ISSUE TITLE
Dire à Jean Paul qu'on a rechangé de nom

### ISSUE THREAD

**Issue by skidlucas** [skidlucas/AtelierDEVINT#10]
C'est maintenant PolyCards.

**Comment by skidlucas** [comment]
Ceci est assez urgent, merci de t'en occuper au plus vite

**Comment by skidlucas** [comment]
tic...tac...

**Comment by Misuke** [comment]
Change pas de assignee comme ça omg..

**Comment by skidlucas** [comment]
bien joué les gars, beau travail
